spring:
  application:
    name: ai-prompt

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2:latest

#    openai:
#      api-key: ${OPENAI_API_KEY}
#      model: gpt-4.1
#  autoconfigure:
#    exclude:
#      - org.springframework.ai.autoconfigure.chat.client.ChatClientAutoConfiguration

